
name: 'Upload files to OSS'
description: 'Upload assets to aliyun OSS'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  region:
    required: false
  endpoint:
    required: false
  key-id:
    required: true
  key-secret:
    required: true
  bucket:
    required: true
  asset-path:
    required: true
  target-path:
    required: true
outputs:
  url:
    description: oss url
runs:
  using: 'node12'
  main: 'lib/index.js'
